import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import googleSvg from "../public/google.svg";
import githubSvg from "../public/github.svg";

import { signIn } from "next-auth/react";

export default function Home() {
  const handleSignIn = (provider) => {
    // the redirect url must be an absolute url!
    const redirect = window.location.href + "/secret";

    signIn(provider, { callbackUrl: redirect });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Authenticate With NextAuth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Sign Up</h1>

      {/* oauth */}
      {/* google */}
      <button onClick={() => handleSignIn("google")} className={styles.oauth}>
        <Image src={googleSvg} width="18" height="18" alt="" />
        <span>Sign up with Google</span>
      </button>
      {/* github */}
      <button onClick={() => handleSignIn("github")} className={styles.oauth}>
        <Image src={githubSvg} width="18" height="18" alt="" />
        <span>Sign up with Github</span>
      </button>

      <form>
        {/* inputs */}
        <div className={styles.inputsContainer}>
          {/* email */}
          <div>
            <label htmlFor="email">Email</label>
            <input disabled type="email" id="email" />
          </div>

          {/* password */}
          <div>
            <label htmlFor="password">Password</label>
            <input disabled type="password" id="password" />
          </div>
        </div>

        {/* sign up button */}
        <button className={styles.signButton}>Sign Up</button>
      </form>
    </div>
  );
}
