import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Secret.module.css";
import topSecret from "../public/top-secret.png";

import { useSession } from "next-auth";

function Secret() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Authenticate With NextAuth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image src={topSecret} alt="" width="320" height="120" />
      <h1>Hello mr {session.user?.name}</h1>
      <p>You are authorized to see this page</p>

      <button>Sign Out</button>
    </div>
  );
}

export default Secret;

export const getServerSideProps = async (context) => {
  // get the session
  const session = await getSession(context);

  // redirect the user if there is no session
  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};
